const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const PORT=process.env.PORT||3000,HOST='0.0.0.0',ADMIN_USER=process.env.ADMIN_USER||'admin',ADMIN_PASSWORD=process.env.ADMIN_PASSWORD||'change-this-admin-password';
const DB=path.join(__dirname,'data','db.json');if(!fs.existsSync(path.dirname(DB)))fs.mkdirSync(path.dirname(DB),{recursive:true});if(!fs.existsSync(DB))fs.writeFileSync(DB,'{"users":[]}');const sessions=new Map();
const db=()=>{try{return JSON.parse(fs.readFileSync(DB,'utf8'))}catch{return{users:[]}}},save=d=>fs.writeFileSync(DB,JSON.stringify(d,null,2));
const hash=(p,s=crypto.randomBytes(16).toString('hex'))=>s+':'+crypto.scryptSync(p,s,64).toString('hex');
const verify=(p,h)=>{try{const[s,d]=h.split(':');return crypto.timingSafeEqual(Buffer.from(d,'hex'),crypto.scryptSync(p,s,64))}catch{return false}};
const id=()=>crypto.randomUUID(),cookies=r=>Object.fromEntries((r.headers.cookie||'').split(';').filter(Boolean).map(x=>{const[a,...b]=x.trim().split('=');return[a,decodeURIComponent(b.join('='))]})),user=r=>sessions.get(cookies(r).sid);
const send=(r,s,x,t='application/json')=>{r.writeHead(s,{'Content-Type':t,'Cache-Control':'no-store'});r.end(t==='application/json'?JSON.stringify(x):x)};
const body=r=>new Promise((ok,no)=>{let b='';r.on('data',c=>{b+=c;if(b.length>2e6)r.destroy()});r.on('end',()=>{try{ok(JSON.parse(b||'{}'))}catch(e){no(e)}})});
const safe=u=>({id:u.id,username:u.username,role:u.role,createdAt:u.createdAt,hasSave:!!u.gameState});
async function app(r,s){const p=new URL(r.url,'http://x').pathname,k=r.method+' '+p;try{
if(k==='POST /api/register'){const b=await body(r),n=String(b.username||'').trim().toLowerCase(),pw=String(b.password||'');if(!/^[a-z0-9_]{3,24}$/.test(n)||pw.length<6)return send(s,400,{error:'Username: 3-24 letters/numbers/underscore. Password: 6+ characters.'});let d=db();if(d.users.some(u=>u.username===n)||n===ADMIN_USER.toLowerCase())return send(s,409,{error:'Username already taken.'});let u={id:id(),username:n,role:'player',passwordHash:hash(pw),createdAt:new Date().toISOString(),gameState:null};d.users.push(u);save(d);const sid=id();sessions.set(sid,u);s.setHeader('Set-Cookie',`sid=${sid}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800`);return send(s,200,{user:safe(u)})}
if(k==='POST /api/login'){const b=await body(r),n=String(b.username||'').trim().toLowerCase(),pw=String(b.password||'');let u;if(n===ADMIN_USER.toLowerCase()&&pw===ADMIN_PASSWORD)u={id:'admin',username:ADMIN_USER,role:'admin'};else{u=db().users.find(x=>x.username===n);if(!u||!verify(pw,u.passwordHash))return send(s,401,{error:'Invalid username or password.'})}const sid=id();sessions.set(sid,u);s.setHeader('Set-Cookie',`sid=${sid}; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800`);return send(s,200,{user:safe(u)})}
if(k==='POST /api/logout'){const sid=cookies(r).sid;sessions.delete(sid);s.setHeader('Set-Cookie','sid=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0');return send(s,200,{ok:true})}
if(k==='GET /api/me')return send(s,200,{user:user(r)?safe(user(r)):null});
const u=user(r);if(k==='GET /api/save'||k==='POST /api/save'){if(!u)return send(s,401,{error:'Login required'});let d=db(),x=d.users.find(v=>v.id===u.id);if(k==='GET /api/save')return send(s,200,{gameState:x?.gameState||null});let b=await body(r);x.gameState=b.gameState||null;x.updatedAt=new Date().toISOString();save(d);return send(s,200,{ok:true})}
if(k==='GET /api/admin/users'||k==='POST /api/admin/reset'||k==='POST /api/admin/delete'){if(!u||u.role!=='admin')return send(s,403,{error:'Administrator access required'});let d=db();if(k==='GET /api/admin/users')return send(s,200,{users:d.users.map(safe)});const b=await body(r),x=d.users.find(v=>v.id===b.id);if(!x)return send(s,404,{error:'Player not found'});if(k.endsWith('/reset'))x.gameState=null;else d.users=d.users.filter(v=>v.id!==b.id);save(d);return send(s,200,{ok:true})}
if(p==='/admin'||p==='/admin/')return file(s,path.join(__dirname,'public/admin.html'),'text/html');if(p==='/')return file(s,path.join(__dirname,'public/index.html'),'text/html');const f=path.normalize(path.join(__dirname,'public',p));if(f.startsWith(path.join(__dirname,'public'))&&fs.existsSync(f)&&fs.statSync(f).isFile())return file(s,f,'text/html');send(s,404,{error:'Not found'})}catch(e){console.error(e);send(s,500,{error:'Server error'})}}
function file(s,f,t){s.writeHead(200,{'Content-Type':t,'Cache-Control':'no-store, no-cache, must-revalidate, proxy-revalidate','Pragma':'no-cache','Expires':'0'});fs.createReadStream(f).pipe(s)}